version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Setup wget
          command: |
              apt-get update
              apt-get install -y wget

      - run:
          name: Install Hugo
          command: |
              wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.tar.gz
              tar -xvf /tmp/hugo.tar.gz -C /usr/bin/

      - run:
          name: Test Hugo
          command: hugo

      - run:
          name: Print the Current Time
          command: ls public