version: 2.1

executors:
  ubuntu:
    docker:
      - image: circleci/golang:stretch

jobs:
  build:
    executor: ubuntu
    working_directory: /tmp/work/blog

    steps:
      - checkout:
          path: /tmp/work

      - run:
          name: Install Hugo
          command: |
              mkdir -p /tmp/hugo_app
              wget -O /tmp/hugo_app/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.tar.gz
              tar -xvf /tmp/hugo_app/hugo.tar.gz -C /tmp/hugo_app

      - run:
          name: Build Hugo Site
          command: |
              /tmp/hugo_app/hugo

      - persist_to_workspace:
          root: /tmp/work
          paths:
            - "*"

  deploy:
    executor: ubuntu
    working_directory: /tmp/work/infrastructure/aws

    steps:
      - attach_workspace:
          at: /tmp/work

      - run:
          name: Setup Terraform
          command: |
              mkdir =p /tmp/terraform_app
              wget -O /tmp/terraform_app/terraform.zip https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
              unzip /tmp/terraform_app/terraform.zip -d /tmp/terraform_app

      - run:
          name: Run Terraform
          command: |
              export TF_WORKSPACE="staging"
              /tmp/terraform_app/terraform init -backend-config "token=${TFE_TOKEN}" -input=false
              unset TF_WORKSPACE

              /tmp/terraform_app/terraform workspace new "${CIRCLE_BRANCH}"

              /tmp/terraform_app/terraform apply -auto-approve -input=false

      - run:
          name: Destroy Terraform Resources
          command: /tmp/terraform_app/terraform destroy -auto-approve -input=false
          when: always
              
      - run:
          name: Delete Terraform Workspace
          command: |
              /tmp/terraform_app/terraform workspace select staging
              /tmp/terraform_app/terraform workspace delete "${CIRCLE_BRANCH}"
          when: always

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build
